# Generated by Django 5.0 on 2023-12-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_color_1_user_color_2_user_mixed_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='color_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='color_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mixed_color',
        ),
        migrations.AddField(
            model_name='user',
            name='mixed_color_number',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
