# Generated by Django 5.0 on 2023-12-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_color_1_remove_user_color_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mixed_color_number',
            field=models.IntegerField(default='0', max_length=200),
        ),
    ]
